version: '3.8'
services:
  arthub:
    image: my-spring-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/arthub-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD:  123
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: arthub-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  123
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
